//@flow
export type CprDirect = {
  "type": string,
  "pnr": string,
  "dob": string,
  "sex": string,
  "status": string,
  "statusDate": string,
  "pnrStatus": string,
  "tutelageDate": string,
  "moveInDate": string,
  "nameAddrressProtectionDate": string,
  "occupation": string,
  "formattedName": string,
  "COName": string,
  "locality": string,
  "standardAddress": string,
  "city": string,
  "postcode": string,
  "postDistrict": string,
  "municipalityCode": string,
  "streetCode": string,
  "houseNumber": string,
  "floor": string,
  "apartment": string,
  "buildingNumber": string,
  "forenames": string,
  "lastname": string,
  "street": string,
  "directMarketingProtectionDate": string
}
